apiVersion: v1
kind: Service
metadata:
  name: aerosense-app
  namespace: default
  labels:
    app: aerosense
    component: testforge
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: aerosense
    component: testforge
